safe_load "autocommands.general"
safe_load "autocommands.ruby"
safe_load "autocommands.editing"
safe_load "autocommands.git"
safe_load "autocommands.formatting"
safe_load "autocommands.alpha"
safe_load "autocommands.skhd"
safe_load "autocommands.indent_line"
