require "autocommands.general"
require "autocommands.ruby"
require "autocommands.editing"
require "autocommands.git"
require "autocommands.formatting"
require "autocommands.alpha"
require "autocommands.skhd"
require "autocommands.lazy"
