return {
  { "akinsho/bufferline.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "mfussenegger/nvim-dap", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "catppuccin", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "echasnovski/mini.diff", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  { "nvim-treesitter/nvim-treesitter-context", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "nvim-neotest/neotest", enabled = false },
  { "olimorris/neotest-rspec", enabled = false },
  { "simrat39/symbols-outline.nvim", enabled = false },
}
