#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 3
bspc config window_gap 20
bspc config border_radius 5
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config click_to_focus true
bspc config apply_floating_atom true
bspc config history_aware_focus true
bspc config normal_border_color "#2E3440"
bspc config focused_border_color "#B48EAD"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) export SSH_AUTH_SOCK

# Setup monitors
~/.config/bspwm/monitors

# Desktop curser
xsetroot -cursor_name left_ptr &

# Compositor
picom &

# Set wallpaper
feh --bg-fill gsettings $HOME/Personal/dotfiles/bspwm/backgrounds/1732259.jpg

# Polybar
$HOME/.config/polybar/launch.sh &

# Clipboard manager
killall -q greenclip
greenclip daemon &

# Dropbox
dropbox start &

# https://github.com/jcs/xbanish
# Hides mouse when you are not using it
xbanish &

xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Accel Profile Enabled" 1, 0
