#!/bin/bash

# https://github.com/phillipberndt/autorandr
# xrandr --output eDP-1 --primary --auto --output DP-1 --auto --dpi 192 --fbmm 621x341
# xrandr --output eDP-1 --off --output DP-1 --primary --auto --dpi 192 --fbmm 621x341

current=$(xrandr --listactivemonitors | grep -v Monitors | grep -Eo '[^ ]+$')
nmonitors=$(xrandr -q | grep " connected " | wc -l)

# echo $current
# echo $nmonitors

external() {
	autorandr external
}

default() {
	autorandr default
}

if [ $nmonitors == 1 ]
then
	default
elif [ $current == "DP-1" ] && [ $nmonitors == 2 ]
then
	external
else
	default
fi
