#!/usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
super + Return
	kitty

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd


super + alt + a
	spicetify apply

#
# Menus
#

# program launcher
super + space
	~/.config/rofi/launcher.sh

# https://github.com/erebe/greenclip
super + alt + s
	rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' -config ~/.config/rofi/clipboard.rasi

super + alt + n
	bash -c '~/.config/rofi/networks.sh';

super + alt + b
	bash -c '~/.config/rofi/bluetooth.sh';

super + alt + p
	~/.config/rofi/powermenu.sh

# Show window menu
super + grave
	rofi -no-fixed-num-lines -no-lazy-grab -show window -config ~/.config/rofi/window.rasi

#
# Monitors
# Automaticaly work out which monitor setup should be used and refresh
#

super + alt + m
	~/.config/bspwm/monitors; bspc wm -r

# Without the bash -c, fish wont execute the command
super + alt + t
	bash -c 'source ~/.config/bspwm/monitors; tv'; bspc wm -r

# Switch to external monitor
super + alt + e
	bash -c 'source ~/.config/bspwm/monitors; external'; bspc wm -r

# Switch to default monitor
super + alt + d
	bash -c 'source ~/.config/bspwm/monitors; default'; bspc wm -r

#
# Print Screen - Requires maim
#
Print
	bash -c 'source ~/Personal/dotfiles/scripts/screenshots.sh; full'

shift + ctrl + Print
	bash -c 'source ~/Personal/dotfiles/scripts/screenshots.sh; copy_selection'

ctrl + Print
	bash -c 'source ~/Personal/dotfiles/scripts/screenshots.sh; save_selection'

#
# Volume
#
XF86AudioMute
	amixer -D pulse sset Master toggle

XF86Audio{Raise,Lower}Volume
	amixer -D pulse sset Master 5%{+,-}

#
# Media Controls
#
XF86Audio{Play,Prev,Next}
	playerctl --player=vlc,spotify {play-pause,previous,next}

#
# Brightness
#
# To adjust the brightness the user must be added to the video group:
# sudo gpasswd -a $USER video
XF86MonBrightness{Up,Down}
	brightnessctl set 5%{+,-}

#
# bspwm hotkeys
#

# Move active window to another desktop
super + shift + {1-9}
	set id (bspc query -N -n); bspc node -d '^ {1-9}'; bspc node -f $id

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + Tab
	bspc node -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

