require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.lsp"
require "user.onenord"
require "user.lualine"
require "user.telescope"
require "user.bufferline"
require "user.trouble"
require "user.cmp"
require "user.rnvimr"
require "user.highlightedyank"
-- require "user.marks" -- Adds mark to Rnvim
require "user.gitsigns"
require "user.alpha"
require "user.togglebool"
require "user.nvim_tree"
