require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.lsp"
require "user.theme"
require "user.lualine"
require "user.telescope"
require "user.bufferline"
require "user.trouble"
require "user.cmp"
require "user.rnvimr"
require "user.highlightedyank"
require "user.gitsigns"
require "user.alpha"
require "user.nvim_tree"
require "user.autocommands"
-- require "user.null-ls"
