#!/bin/bash

# Simple script to instll Nvim from the required release channel

# URL="https://github.com/neovim/neovim/releases/download/stable/nvim.appimage"
URL="https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"

RESPONSE=$(curl --write-out '%{http_code}' --silent --output /dev/null $URL)
TARGET="$HOME/.local/bin/nvim"

if [ $RESPONSE != 404 ]
then
	rm -f $TARGET
	curl -fSL -o $TARGET $URL
	chmod u+x $TARGET
else
	echo "Download not found"
fi
